name       : haskell-bitarray
version    : 0.0.1.1
release    : 1
source     :
    - http://hackage.haskell.org/package/bitarray-0.0.1.1/bitarray-0.0.1.1.tar.gz : b27f6f1065053a0e8e24fbf9382b7060af9962d8d150b631c682c0c58469d802
license    : BSD-3-Clause
component  : programming.haskell
summary    : Mutable and immutable bit arrays. 
description: |
    Mutable and immutable bit arrays. 
builddeps  :
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
